const industryList = [
  // Technology & Software (Sqysh's Category)
  'Software Development',
  // Business & Finance
  'Accountant',
  'Financial Advisor',
  'Tax Consultant',
  'Bookkeeper',
  'Investment Banker',
  'Insurance Agent',
  'Mortgage Broker',
  'Business Coach',
  'CFO',
  'Controller',
  'Auditor',
  'Credit Analyst',
  'Financial Planner',
  'Wealth Manager',

  // Legal
  'Attorney',
  'Lawyer',
  'Paralegal',
  'Legal Consultant',
  'Corporate Lawyer',
  'Family Lawyer',
  'Criminal Defense Attorney',
  'Personal Injury Lawyer',
  'Real Estate Attorney',
  'Immigration Lawyer',
  'Tax Attorney',
  'Patent Attorney',
  'Bankruptcy Lawyer',

  // Healthcare
  'Doctor',
  'Physician',
  'Surgeon',
  'Dentist',
  'Orthodontist',
  'Chiropractor',
  'Physical Therapist',
  'Nurse',
  'Veterinarian',
  'Optometrist',
  'Psychologist',
  'Psychiatrist',
  'Pharmacist',
  'Medical Device Sales',
  'Healthcare Administrator',
  'Nutritionist',
  'Mental Health Counselor',
  'Speech Therapist',

  // Real Estate & Construction
  'Residential Real Estate Agent',
  'Commercial Real Estate Agent',
  'Real Estate Broker',
  'Property Manager',
  'Real Estate Developer',
  'General Contractor',
  'Architect',
  'Interior Designer',
  'Home Inspector',
  'Appraiser',
  'Construction Manager',
  'Electrician',
  'Plumber',
  'HVAC Technician',
  'Roofer',
  'Landscaper',
  'Flooring Specialist',
  'Kitchen & Bath Designer',
  'Civil Engineer',

  // Sales & Marketing (Non-Digital)
  'Sales Representative',
  'Marketing Manager',
  'Brand Manager',
  'Public Relations Specialist',
  'Advertising Executive',
  'Sales Manager',
  'Account Manager',
  'Business Development Manager',
  'Customer Success Manager',
  'Event Planner',
  'Content Creator',
  'Copywriter',

  // Professional Services (Non-Tech)
  'HR Consultant',
  'Executive Coach',
  'Training Specialist',
  'Organizational Development',
  'Project Manager',
  'Operations Manager',
  'Quality Assurance',
  'Process Improvement Specialist',

  // Creative & Media
  'Photographer',
  'Videographer',
  'Graphic Designer',
  'Artist',
  'Musician',
  'Writer',
  'Editor',
  'Journalist',
  'Creative Director',
  'Brand Designer',
  'Marketing Creative',
  'Content Producer',
  'Social Media Content Creator',

  // Education & Training
  'Teacher',
  'Professor',
  'Principal',
  'Education Consultant',
  'Tutor',
  'Training Manager',
  'Corporate Trainer',
  'Curriculum Developer',
  'Academic Advisor',

  // Manufacturing & Industrial
  'Manufacturing Manager',
  'Quality Control',
  'Supply Chain Manager',
  'Logistics Coordinator',
  'Operations Director',
  'Plant Manager',
  'Industrial Engineer',
  'Production Manager',
  'Warehouse Manager',
  'Distribution Manager',

  // Retail & Hospitality
  'Retail Manager',
  'Store Owner',
  'Restaurant Owner',
  'Hotel Manager',
  'Event Coordinator',
  'Catering Manager',
  'Food Service Manager',
  'Hospitality Manager',
  'Travel Agent',
  'Tourism Specialist',
  'Specialty Coffee Industry',

  // Transportation & Logistics
  'Trucking Company Owner',
  'Logistics Manager',
  'Supply Chain Consultant',
  'Freight Broker',
  'Transportation Coordinator',
  'Fleet Manager',
  'Shipping Manager',
  'Courier Service',

  // Personal Services
  'Hair Stylist',
  'Barber',
  'Massage Therapist',
  'Personal Trainer',
  'Life Coach',
  'Wedding Planner',
  'Personal Chef',
  'Cleaning Service',
  'Lawn Care Service',
  'Pet Groomer',
  'Dog Trainer',
  'Personal Assistant',

  // Automotive
  'Auto Mechanic',
  'Auto Dealer',
  'Auto Body Repair',
  'Car Detailing',
  'Tire Shop Owner',
  'Auto Parts Dealer',
  'Automotive Service Manager',

  // Home Services
  'Handyman',
  'Painter',
  'Carpet Cleaner',
  'Window Cleaner',
  'Pest Control',
  'Security System Installer',
  'Pool Service',
  'Appliance Repair',

  // Financial Services
  'Bank Manager',
  'Loan Officer',
  'Credit Union Manager',
  'Investment Advisor',
  'Estate Planning Attorney',
  'Trust Officer',
  'Retirement Planning Specialist',
  'Payroll Services',

  // Non-Profit & Government
  'Non-Profit Director',
  'Fundraising Specialist',
  'Grant Writer',
  'Social Worker',
  'Government Official',
  'Public Administrator',
  'Community Organizer'
].sort()

export default industryList
