export const sliceUser = 'userApi'
export const sliceSettings = 'settingsApi'
export const sliceNotification = 'notificationApi'
export const sliceAuth = 'authApi'
export const sliceParley = 'parleyApi'
